version: '3'

services:
  mongodb:
    image: mongo
    container_name: my_mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
